import numpy as np
from web3 import Web3
import json
import time

class Web3BaseClient:
    def __init__(self, rpc_url, private_key):
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))
        if not self.w3.is_connected():
            raise ConnectionError("Failed to connect to Ethereum node.")
        self.account = self.w3.eth.account.from_key(private_key)
        self.wallet_address = self.account.address
        print(f"[*] Base node initialized. Operating as: {self.wallet_address}")

class AIPromptExecutionNode(Web3BaseClient):
    def __init__(self, rpc_url, private_key, contract_address, abi_path):
        super().__init__(rpc_url, private_key)
        
        self.contract_address = self.w3.to_checksum_address(contract_address)
        with open(abi_path, 'r') as file:
            contract_abi = json.load(file)
            
        self.contract = self.w3.eth.contract(address=self.contract_address, abi=contract_abi)
        print("[*] AI Execution Node loaded smart contract interfaces.")

  def verify_and_execute(self, token_id, user_address):
        """验证用户是否拥有访问权，如果拥有则模拟调用大模型"""
        try:
            ens_name = self.w3.ens.name(user_address)
            display_name = ens_name if ens_name else user_address
        except:
            display_name = user_address
        print(f"[*] Verifying access for User: {display_name} on Prompt NFT: {token_id}")
        
        has_access = self.contract.functions.hasAccess(token_id, user_address).call()
        if not has_access:
            print("[!] Access Denied: User has not purchased this prompt.")
            return None
            
        print("[+] Access Granted. Fetching encrypted prompt from IPFS...")
        time.sleep(1) 
        return f"Simulated high-quality AI output generated by Prompt #{token_id}"

    def analyze_market_ratings(self, raw_ratings_batch):
        """
        利用 numpy 和列表推导式处理批量评分数据，
        用于在链下计算提示词市场的健康度和波动率。
        """
        valid_ratings = [rating for rating in raw_ratings_batch if 0 < rating <= 5]
        
        if not valid_ratings:
            return {"mean": 0, "std_dev": 0, "status": "No valid data"}          
        ratings_array = np.array(valid_ratings)
        mean_score = np.mean(ratings_array)
        std_dev = np.std(ratings_array) 
        
        return {
            "mean": round(mean_score, 2),
            "std_dev": round(std_dev, 2),
            "total_valid_samples": len(valid_ratings),
            "status": "Healthy" if mean_score > 3.5 else "Needs Review"
        }

if __name__ == "__main__":
    MOCK_RPC = "https://eth-sepolia.g.alchemy.com/v2/YOUR_API_KEY"
    MOCK_PK = "0000000000000000000000000000000000000000000000000000000000000000" 
    
    print("--- PromptProof AI Node System Booting ---")
    try:
        node = AIPromptExecutionNode(MOCK_RPC, MOCK_PK, "0x...", "abi.json")
    except Exception as e:
        print(f"[!] Blockchain connection bypassed for offline logic test: {e}")
        mock_raw_ratings = [5, 4, 0, 5, -1, 3, 4, 5, 10, 2] 
        print(f"\n[*] Processing raw rating batch: {mock_raw_ratings}")
      
        analysis_result = AIPromptExecutionNode.analyze_market_ratings(None, mock_raw_ratings)
        print(f"[+] Market Analysis Result: {analysis_result}")
